name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml.lock') }}-${{ hashFiles('**/package.yaml') }}
      - uses: actions/setup-haskell@2215b2cb657e9dd555e7d634509d859983e7aa1e
        with:
          ghc-version: "8.8.4"
          stack-version: "latest"
          enable-stack: true
      - run: stack build --system-ghc
      - run: stack test --system-ghc
      - name: Run with --version
        run: stack run --system-ghc -- --version
