name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml.lock') }}-${{ hashFiles('**/package.yaml') }}
      - if: matrix.os  == 'macos-latest'
        name: Install stack
        run: brew install haskell-stack
      - run: stack --system-ghc build
      - run: stack --system-ghc test
      - name: Run with --version
        run: stack --system-ghc run -- --version
